### PR TITLE
Increased heap size for learner record

### PR DESCRIPTION
**Pull request by mmackiewicz1**
Increased initial java heap size to 1GB and maximum heap size to 4GB for learner record.

### CODE REVIEW

**Comment by willh** [comment]
Can we compare to max available for Learner Record in production? I think we might have set this to 7g in the release we scaled Learner Record - Pritpal may recall for sure

**Comment by mmackiewicz1** [comment]
@willh Thanks for the feedback. I was able to check all environments but production and all of them had about 800MB of maximum heapsize. I will look into this.

**Comment by pritpalp** [comment]
Added this to the release branch

**Comment by pritpalp** [comment]
Closing as we've release this now

**Pull request closed without merging**
